substitutions:
# Customize with your preferences
# Devicename is the name showed about the device
# Devicename_id is the identity used in home assistant
# board_type it's esp01_1m for SonOFF Dual
# static_ipaddr it's for the ip assignet to the SofOFF Dual
#
# Remember that you must have some infos in your ESPHome Secret like:
# ota_password  : the Over The Air password is used to login in ESPHome devices to update it, can be one for all device or one for each device
#
# wifi_ssid     : SSID of the name of the first wifi to try to connect to
# wifi_password : First wifi password
# wifi2_ssid    : Alternative WiFi
# wifi2_password: Alternative WiFi Password
#
# gateway       : Network gateway (like your router ip address)
# subnet        : Lan Subnet, home user tipical use 255.255.255.0
# dns1          : DNS server, if you don't know use 8.8.8.8
# ap_password   : Access Point mode password, if the device cannot connect to any of the specified wifi, the device will generate a wifi to which you can connect to use it
#
# time_zone     : Your time zone like Europe/Rome
# ntp_servers   : A NTP Server from https://www.ntppool.org/

  devicename:    SonOFF Dual
  devicename_id: sonoff-dual
  board_type:    esp01_1m
  static_ipaddr: 192.168.0.X

esphome:
  name:  $devicename_id

  # On boot all switch must be off
  on_boot:
    priority: -10
    then:
      - switch.turn_off: relay1
      - switch.turn_off: relay2

esp8266:
  board: $board_type

logger:

api:
  encryption:
    key: !secret api_encryption

ota:
  password:    !secret ota_password
  id:          my_ota

wifi:
  networks:
  - ssid:      !secret wifi_ssid
    password:  !secret wifi_password
  - ssid:      !secret wifi2_ssid
    password:  !secret wifi2_password

  manual_ip:
    static_ip: $static_ipaddr
    gateway:   !secret gateway
    subnet:    !secret subnet
    dns1:      !secret dns1

  ap:
    ssid:      $devicename Hotspot
    password:  !secret ap_password

captive_portal:

web_server:
  port: 80

time:
  - platform: sntp
    timezone: !secret time_zone
    servers:  !secret ntp_servers

text_sensor:
  - platform: version
    name: $devicename ESPHome Version
  - platform: wifi_info
    ip_address:
      name: $devicename IP
    ssid:
      name: $devicename SSID
    bssid:
      name: $devicename BSSID

# SonOff Dual R2
# https://esphome.io/cookbook/sonoff-dual-light-switch.html

binary_sensor:
  - platform: status
    name: $devicename Status

  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: $devicename Button 1
    on_press:
        - switch.toggle: relay1

  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    name: $devicename Button 2
    on_press:
        - switch.toggle: relay2

switch:
  - platform: restart
    name: $devicename Reboot

  - platform: gpio
    name: $devicename Switch 1
    pin: GPIO12
    id: relay1

  - platform: gpio
    name: $devicename Switch 2
    pin: GPIO5
    id: relay2

sensor:
  - platform: uptime
    name: $devicename Uptime

  - platform: wifi_signal
    name: $devicename WiFi Signal
    update_interval: 60s

status_led:
  pin:
    number: GPIO13
    inverted: yes
